# Generated by Django 3.2 on 2021-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='Auton rengas', max_length=20)),
                ('packagesize', models.CharField(default=3, max_length=20)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unitsinstock', models.IntegerField(default=3)),
                ('companyname', models.CharField(default='Oy Firma Ab', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='Oy Firma Ab', max_length=50)),
                ('contactname', models.CharField(default='Aku', max_length=50)),
                ('address', models.CharField(default='Paratiisitie 13', max_length=100)),
                ('phone', models.CharField(default='313313', max_length=20)),
                ('email', models.CharField(default='aku@ankka.com', max_length=50)),
                ('country', models.CharField(default='Finland', max_length=20)),
            ],
        ),
    ]
